/**
 * oss#137 — the default for a route nobody classified.
 *
 * route-coverage.test.ts already proves that no route registered TODAY
 * answers an anonymous caller. This file asks the other question, the one a
 * snapshot of today's table cannot answer: what happens to the NEXT route.
 *
 * Under prefix matching, "protected" was a property of the spelling of the
 * path. `/api`, `/sessions` and `/a2a` were guarded, and a route registered
 * anywhere else in the tree was open because nothing had ever classified it.
 * That is fail-open by default: the author of a new route had to remember to
 * put it under a guarded prefix, and forgetting produced a working, open
 * endpoint rather than an error. This is a published MIT runtime, so the
 * "new route" is not hypothetical: an embedder holding `fastifyInstance`
 * registers routes on this exact server.
 *
 * So the route under test here is registered from outside webhook-server.ts,
 * on a path nobody guarded, exactly as an embedder or a future
 * registerRoutes() line would. It has to refuse an anonymous caller because
 * nothing declared it public, not because its path happens to start with the
 * right five characters.
 *
 * Every refusal below is paired with a positive control that drives the same
 * route with the credential this runtime materialized for itself. Without
 * that pair a 401 proves nothing: a typo in the URL, a route that never
 * registered, or a guard that refuses everything would all produce the same
 * red-to-green transition. The control says the route exists, is reachable,
 * and answers 200 to a caller that holds the token; the refusal then says
 * the guard is what stopped the anonymous one.
 */

import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { mkdtempSync, rmSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { WebhookServer } from "../webhook-server.js";

describe("oss#137: an unclassified route is born closed", () => {
  let server: WebhookServer;
  let stateDir: string;
  let token: string;
  const saved: Record<string, string | undefined> = {};

  beforeAll(() => {
    for (const key of ["ENGINE_API_TOKEN", "CODESPAR_STATE_DIR"]) {
      saved[key] = process.env[key];
    }
    // The default install: the operator supplied nothing, so the runtime
    // materializes its own credential. Same starting point as
    // anonymous-access.test.ts.
    delete process.env.ENGINE_API_TOKEN;
    stateDir = mkdtempSync(join(tmpdir(), "codespar-default-closed-"));
    process.env.CODESPAR_STATE_DIR = stateDir;
    server = new WebhookServer({ port: 0 });

    // Registered from outside the server file, before the first request, the
    // way an embedder does it. Neither path is under `/api`, `/sessions` or
    // `/a2a`, and neither is declared public anywhere.
    server.fastifyInstance.get("/internal/probe", async () => ({ ok: true }));
    server.fastifyInstance.post("/integrations/acme/callback", async () => ({ ok: true }));

    // The credential a local client reads off disk. It is generated by this
    // test's own server into this test's own temp directory and dies with it.
    token = readFileSync(join(stateDir, "api-token"), "utf8").trim();
  });

  afterAll(() => {
    for (const [key, value] of Object.entries(saved)) {
      if (value === undefined) delete process.env[key];
      else process.env[key] = value;
    }
    rmSync(stateDir, { recursive: true, force: true });
  });

  it("refuses an anonymous GET on a route outside the guarded prefixes", async () => {
    const res = await server.inject({ method: "GET", url: "/internal/probe" });
    expect(
      res.statusCode,
      "a route nobody classified answered an anonymous caller",
    ).toBe(401);
    expect(JSON.parse(res.body).code).toBe("api_token_required");
  });

  it("positive control: that same route answers 200 with the runtime's credential", async () => {
    // If this were 404 the refusal above would be meaningless, and if it were
    // 401 the guard would be refusing everyone rather than defaulting closed.
    const res = await server.inject({
      method: "GET",
      url: "/internal/probe",
      headers: { authorization: `Bearer ${token}` },
    });
    expect(res.statusCode).toBe(200);
    expect(JSON.parse(res.body)).toEqual({ ok: true });
  });

  it("refuses an anonymous POST on a route outside the guarded prefixes", async () => {
    const res = await server.inject({
      method: "POST",
      url: "/integrations/acme/callback",
      payload: {},
      headers: { "content-type": "application/json" },
    });
    expect(res.statusCode).toBe(401);
  });

  it("positive control: that POST route answers 200 with the credential", async () => {
    const res = await server.inject({
      method: "POST",
      url: "/integrations/acme/callback",
      payload: {},
      headers: { "content-type": "application/json", authorization: `Bearer ${token}` },
    });
    expect(res.statusCode).toBe(200);
  });

  it("refuses a target that matched no route at all", async () => {
    // Nothing registered this path, so no handler was ever going to run and
    // the old answer was Fastify's 404. It is listed here because it is the
    // same decision: a target the guard cannot tie to a declared-public route
    // is refused rather than waved through. A caller holding the token still
    // gets the 404, which the control below shows.
    const res = await server.inject({ method: "GET", url: "/nope/nothing" });
    expect(res.statusCode).toBe(401);
  });

  it("positive control: an authenticated caller still gets 404 for a path that does not exist", async () => {
    // The refusal above must be the credential check, not the guard having
    // swallowed the router. With the token, the router answers for itself.
    const res = await server.inject({
      method: "GET",
      url: "/nope/nothing",
      headers: { authorization: `Bearer ${token}` },
    });
    expect(res.statusCode).toBe(404);
  });

  // ── The other direction: nothing that was open may close ──────────

  it("keeps /health open to the container healthcheck, GET and HEAD alike", async () => {
    // docker-compose.yml probes GET /health with a bare node http.get and no
    // credential; a load balancer probing the same path commonly uses HEAD,
    // which Fastify auto-registers from the GET route and reports as its own
    // entry in the route table. A public list keyed by method would answer
    // 401 to HEAD and mark the container unhealthy, so both are pinned.
    const get = await server.inject({ method: "GET", url: "/health" });
    expect(get.statusCode).toBe(200);
    const head = await server.inject({ method: "HEAD", url: "/health" });
    expect(head.statusCode).toBe(200);
  });

  it("keeps the /v1 mirror of /health open too", async () => {
    expect((await server.inject({ method: "GET", url: "/v1/health" })).statusCode).toBe(200);
  });

  it("keeps A2A discovery open, because peers fetch it before any credential exists", async () => {
    const res = await server.inject({ method: "GET", url: "/.well-known/agent.json" });
    expect(res.statusCode).toBe(200);
  });

  it("keeps provider webhooks reachable without a bearer token", async () => {
    // Providers sign, they do not send bearer tokens. Whatever these routes
    // answer, it must not be the credential refusal. (What they do with an
    // unsigned payload is #138's question, not this file's.)
    for (const url of ["/webhooks/github", "/webhooks/vercel", "/webhooks/sentry", "/webhooks/deploy"]) {
      const res = await server.inject({
        method: "POST",
        url,
        payload: {},
        headers: { "content-type": "application/json" },
      });
      expect(res.statusCode, `${url} started demanding a bearer token`).not.toBe(401);
    }
  });

  it("keeps the OAuth install and callback pair open", async () => {
    // A browser arrives here mid-redirect and the provider calls back with a
    // code; neither can attach a bearer token.
    for (const url of [
      "/api/slack/install",
      "/api/slack/callback",
      "/api/discord/install",
      "/api/github/install",
      "/api/github/callback",
    ]) {
      const res = await server.inject({ method: "GET", url });
      expect(res.statusCode, `${url} started demanding a bearer token`).not.toBe(401);
    }
  });
});
